import Head from 'next/head';
import { Jost } from 'next/font/google';
import { useEffect } from 'react';
import { useRecoilState } from 'recoil';

import prisma from '@/lib/prisma';
import SideBar from '@/components/Sidebar';
import Suggestions from '@/components/Suggestions';
import { Feedback, User } from '@/types';
import { feedbackListState } from '@/atoms/FeedbackAtom';
import { currentUserState } from '@/atoms/currentUserAtom';

const jost = Jost({ subsets: ['latin'] });

type Props = {
  feedbackList: Feedback[];
  currentUser: User;
};

export default function Home({ feedbackList, currentUser }: Props) {
  const [_f, setFeedbacksList] = useRecoilState<Feedback[]>(feedbackListState);
  const [_u, setCurrentUser] = useRecoilState<User>(currentUserState);
  useEffect(() => {
    setFeedbacksList(feedbackList);
    setCurrentUser(currentUser);
  }, []);

  return (
    <>
      <Head>
        <title>Product Feedback App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/svg+xml" href="/favicon-32x32.png" />
      </Head>
      <main
        className={`${jost.className} className="flex flex-col min-h-screen font-sans bg-white-dark`}
      >
        <div className="flex lg:flex-row flex-col justify-center md:py-14 md:px-10 lg:py-[94px]">
          <SideBar />
          <Suggestions />
        </div>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const feedbackList = await prisma.feedback.findMany();
  const currentUser = await prisma.user.findFirst();

  return {
    props: { feedbackList, currentUser },
  };
}
